In [17]:
import pandas as pd
import numpy as np

In [18]:
# Assuming all LEDs use the same current
I_LED = 0.02 # mA
U_sys = 4.2 # V
x_LED_PWM = 0.5 # 50% duty cycle

# TODO check the order of the indices from the Program
indices                 = ['UV', 'Red', 'Blue', 'Green', 'Purple', 'Orange', 'IR']
specific_radiant_power = np.array([6.0, 4.0, 5.0, 4.5, 5.5, 4.0, 3.0]) # mW/cm^2

# Single hole
diameter = 7 # mm
cross_section = np.pi * (diameter/10/2)**2 # cm^2
radiant_power = cross_section * specific_radiant_power / 1000 # W

radiant_power_df = pd.DataFrame(radiant_power, index=indices, columns=['Radiant Power (W)'])

num_colors = len(indices)
plate_row = 8
plate_col = 12

# Populate the matrix with random values from 0 to 2^16-1
M = np.random.randint(0, 2**16-1, (num_colors, plate_row, plate_col))
M[0, 0, 0] = 0
M = np.ones((num_colors, plate_row, plate_col)) * (2**16-1) / 1000

# Scale the matrix to the range of 0 to 1
M_scaled = M / (2**16-1)

In [19]:
# Multiply M by the radiant power in the diretions of the colors
M_radiant_power = np.multiply(M_scaled, radiant_power[:, np.newaxis, np.newaxis]) # or *
P_r = np.sum(M_radiant_power) # W

# TODO multiply the current by the number of active LEDs???
num_active_LED = np.sum(M_scaled > 0)
P_LED = num_active_LED * I_LED * U_sys * x_LED_PWM # W

Q_LED_tot = P_LED - P_r # W
print(f"Total LED power: {P_LED:.2f} W")
print(f"Total radiant power: {P_r:.2f} W")
print(f"Total LED power loss: {Q_LED_tot:.2f} W")


Total LED power: 28.22 W
Total radiant power: 0.00 W
Total LED power loss: 28.22 W


Problem that with constant light emitted, the power consumption is the same and does not decrease with a lower M: what is x_LED_PWM??

In [20]:
a = np.ones((2, 3, 4))
b = np.array([2, 3])

c = np.multiply(a, b[:, np.newaxis, np.newaxis])
print(c)
print(np.sum(c, axis=1))

[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]]
[[6. 6. 6. 6.]
 [9. 9. 9. 9.]]
